
services:
  nuxtapp:
    working_dir: /app
    build:
      context: ./frontend
      dockerfile: ./frontend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    tmpfs:
      - /tmp
    command: /bin/sh -c "cd /app && yarn run dev --host"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  frontend_node_modules:
